### ISSUE TITLE
Doubling extensions in the instant search

### ISSUE THREAD

**Issue by ZyXoid** [joomla/jed-issues#104]
Some extensions repeat several times in search results. I think this is because separate words are making separate search results which then are merged. 

**To Reproduce**
1. Go to https://extensions.joomla.org/instant-search
2. Type in the search filed word by word: "facebook page reviews"
3. See repeated extensions

**Screenshots**
![Screenshot_jed](https://user-images.githubusercontent.com/3471561/59044420-c4303680-8886-11e9-81c3-e7ac9e4b084c.jpg)

**Comment by anibalsanchez** [comment]
I have reproduced the issue. 

It's not clear why it is happening.

The extension is repeated in the Algolia index. The JED Indexer only submits it once. If I reindex everything now, then the issue is solved https://extensions.joomla.org/instant-search/?q=facebook%20page%20reviews&hPP=10&idx=jed_live&p=0

Let's keep the ticket open to gather more info.

**Comment by slashdottom** [comment]
3 more examples of duplicate search results;

Phoca Photo
https://extensions.joomla.org/instant-search/?q=Phoca%20Photo
In this example, the thumbnail lead description are different and one result has the Joomla4 badge but the other doesn't, however they point to the same URL.

Contact Information
https://extensions.joomla.org/instant-search/?q=Contact%20Information
In this example, Contact Information Plg and Contact Information Mod point to the same URL.

Keptify Recovery
https://extensions.joomla.org/instant-search/?q=Keptify%20Recovery
This example shows 3 of the exact same results all pointing to the same URL.

**Comment by tassosm** [comment]
I started facing the same issue with one of my extensions a few weeks ago when I modified the Tags in the extension's editing page. 

![image](https://user-images.githubusercontent.com/6807469/59584131-ee36f380-90e5-11e9-80cd-7106036b3682.png)

The issue was automatically resolved though in the next (Algolia) index update.

If you check again the "facebook page reviews" issue, it can't be reproduced anymore.

**Comment by slashdottom** [comment]
In April this year I discovered 341 duplicate search results of no more than 2 results for each extension that pointed to the same url. Other than 13 of the duplicates found, all other duplicates (328) appeared to follow the pattern of being 19 pages apart or exactly 341 listings apart. I had to move onto something else at the time and didn't have enough time to do further research and write about my findings. Since then the number of duplicate search results has drastically been reduced, possibly due to a re-index between then and now. However as pointed out above, the issue still appears to continue.

**Comment by slashdottom** [comment]
In my post above, the Keptify Recovery extension showed 3 of the exact same search results, however rechecking that example now shows 4 of the same search results.

**Comment by anibalsanchez** [comment]
Thanks for reporting. I'm going to check the query as soon as I have a couple of hours.

**Comment by tassosm** [comment]
Another issue on https://extensions.joomla.org/instant-search/?q=forms where FlexiContent and Payment Form extensions appear twice.

**Comment by anibalsanchez** [comment]
It happens that there are actually duplicated extensions, and the search indexer shows it.

I've just fixed the indexer query to avoid them. So, this issue is fixed.

Data cleansing on published extensions is needed to solve the duplication. Let's continue here #110
