### ISSUE TITLE
JED4 Security Checkup of Extensions

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#133]
Based on the idea of adding RIPS to JED, could we use RIPS to check extensions in the manual checkup of extensions?

It can greatly improve the security of the ecosystem. But, it also adds a new manual step to the task of reviewing extensions.

**Comment by anibalsanchez** [comment]
For reference, the point has been discussed here: https://github.com/joomla/jed-issues/issues/67#issuecomment-576114237

**Comment by hdouglassmith** [comment]
> It can greatly improve the security of the ecosystem. But, it also adds a new manual step to the task of reviewing extensions.

I think the way to describe this is "No Pain, No Gain"

From a personal experience as an integrator, there are perhaps 3 or 4 extension developers I consider as 'go to' and will always check out first, the other 9000+ I pretty much ignore because there is no way of testing quality. This comes from experience of 10+ years.

Joomla! has to up its game from a professionalism standpoint. To do that we need to set out our plans (Roadmap), strive hard to make target deadlines (Release code) and push quality and security (JED with a level of certification).

We have to find a way to do this.

**Comment by anibalsanchez** [comment]
I've also copied @JazParkyn to know her view on how we could add the **Security Review** on the context of the JED4 project scope.

I have experience working with similar static analysis tools on corporate solutions. In my view, there is a mismatch between the corporate architectural model of these services and our need for processing a big number of small extensions; so I don't know how we could overcome this difference.

**Comment by anibalsanchez** [comment]
At this point, this issue is more like a "nice to have" than something that we can do today.

Realistically, better if we improve the JED Checker for Joomla 4 #118

Since this issue is not actionable today, I'm closing ti, and moving our efforts to JED Checker #118
