### ISSUE TITLE
None valid URLS "Compatible with J4" & "Custom Fields"

### ISSUE THREAD

**Issue by conconnl** [joomla/jed-issues#155]
Both mentioned buttons are not valid URLs.
They are not usable by Google, do not use any correct SEO methods or whatsoever.
They are just search filters, which decrease the quality of the site.

The person created them should convert them to real URLs with a purpose, which can also be shared with others and are easy to remember.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/11913918/79329991-07344f00-7f19-11ea-82fb-3e45e5bc028f.png">

**Comment by anibalsanchez** [comment]
This is a tough one. At this point, com_jed v3 is on a feature freeze and we are not adding new features. That's mainly why when I have to add the new menu items, I crafted these URLs as the way to feature on the main menu **Extensions Compatible with J4 Alpha** and **Custom Fields**.

At this time, the only solution to the issue is unpublishing the menu items.

@JazParkyn What do you think? Do we tolerate the menu items or do we unpublish them?

**Comment by anibalsanchez** [comment]
I've removed the links. Case closed.
