### ISSUE TITLE
[JED] - search includes unpublished extensions

### ISSUE THREAD

**Issue by JazParkyn** [joomla/jed-issues#165]
Search string: Instagram

https://extensions.joomla.org/instant-search/?jed_live%5Bquery%5D=instagram&jed_live%5BrefinementList%5D%5Btype%5D%5B0%5D=Free

Results contain:
![image](https://user-images.githubusercontent.com/6943227/80398043-f7205600-88ae-11ea-9b07-8079615957ad.png)

Clicking on the extension gives:
![image](https://user-images.githubusercontent.com/6943227/80398068-00a9be00-88af-11ea-9630-d622e942542a.png)

**Comment by anibalsanchez** [comment]
The current search indexer runs weekly and processes all extensions. In the meantime, these differences are found.  Similarly, an issue caused by the same source was reported the past week #157 

It would be better if the indexer runs processing only the modifications at every hour. In theory, the ucm_content has the timestamps to process only the changes. It would be better perfect if the extension is re-indexed every time that the data is changed, per event.

At this point, if the search is going to be replaced on JED4, I'm unsure if it safe to invest more time in the current indexer.

**Comment by anibalsanchez** [comment]
I'll check if it can be improved to increase the frequency with a few tweaks (and without running out of credits, indexing the information that it is already indexed).

**Comment by anibalsanchez** [comment]
As a quick fix, I've increased the frequency of the indexing cron job. This reduces the chance of finding unpublished extensions.

**Comment by anibalsanchez** [comment]
As discussed, we solve the issue with the new frequency. No more changes by now.
