### ISSUE TITLE
Unable to read JED product reviews 

### ISSUE THREAD

**Issue by rockybranch** [joomla/jed-issues#191]
Appears to be some URL problem - For example, I was looking at the Sourcerer product , and rolled over the "170 Reviews" link in the upper left of the page. 
That URL is "https://extensions.joomla.org/write-review/review/add?extension_id=306"
If I click it, it takes me to a "write a review" page.

I dont want to write a review, I want to read what other people have to say about it.

Problem is not just with Sourcerer, it is the same with all other products I tried.

**Comment by rockybranch** [comment]
Update:  Workaround:
If I scroll down the page, there are 3 tabs, "Full Description", "Reviews" and "Other Extensions"
Clicking the "Reviews" tab takes me to a readable list of reviews.
In the case of Sourcerer, this is "https://extensions.joomla.org/extension/sourcerer/#reviews"

**Comment by conconnl** [comment]
@Llewellynvdm 
This part of the code seems to be wrong.
https://github.com/joomla/jed-dev/blob/develop/public_html/components/com_jed/views/extension/tmpl/default.php#L210-L214

It results to the Add Review URL instead of the view review URL
I expect it's replacing:
`<a href="<?php echo $reviewLink; ?>">`
With:
`<a href="#reviews" data-toggle="tab"><?php echo $reviewTabTitle; ?>`

Could you take a quick look?

**Comment by Llewellynvdm** [comment]
Looks correct to me, since that code results seems to allow you to add more reviews. But okay... if we wanted to instead show them the existing comment in the tab below the [following should work](https://github.com/joomla/jed-dev/blob/develop/public_html/components/com_jed/views/extension/tmpl/default.php#L210):
```html
<?php if ($item->num_reviews->value) : ?>
	<a href="#reviews" data-toggle="tab">
		<?php echo JText::plural('COM_JED_NUM_REVIEWS', $item->num_reviews->value); ?>
	</a>
<?php endif; ?>
```
But this will not scroll the page down to the comment, just switch the tab... we will need more to achieve that.
