### ISSUE TITLE
unable to write a review

### ISSUE THREAD

**Issue by toonetcreation** [joomla/jed-issues#226]
hi,

I'm not able to write a review for joomshaper sp page builder
see here : http://prntscr.com/12u5168

thanks

**Comment by mfleeson** [comment]
hi
What is your registered user name on the extensions site?

**Comment by toonetcreation** [comment]
username is : toonetcreation

**Comment by Llewellynvdm** [comment]
The current JED at times have a session issue which we have opt not to try and fix, since we are planning to move the whole JED to Joomla 4 and therefore a complete new component is being build. For most of us we don't have this issue... and so it may help to use another browser like Firefox, and you may need to logout clear your cache of your browser, log back in... browse around to make sure your current session is detected, then try to make a review again.

Let me know if your not having success, and apology for the delayed reply.

**Comment by toonetcreation** [comment]
ok thanks for the feedback.
L.

**Comment by Llewellynvdm** [comment]
I will close this issue, and if you would like to pick it up again. you are very welcome to reply on the closed issue and if needed we will open it back up.
