### ISSUE TITLE
Add text note with example usage below Video param

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#231]
Hello,
Adding a new product is an important part for each developer who want to get their extension to be listed at the JED.
And it would be good to add a video to the product page.
However, the usage example is not clear.

I suggest adding a note from the Video param tooltip at the "suggest a product" page:
https://extensions.joomla.org/add-an-extension/extension/edit/

<img width="1402" alt="Снимок экрана 2021-09-04 в 19 54 11" src="https://user-images.githubusercontent.com/3432048/132102480-99e5964d-7734-42cf-8c65-45c22b10d9be.png">

**Comment by Llewellynvdm** [comment]
Good question, just that we are **no longer doing any changes to JED3** unless security related. So only security updates excepted at this point on JED 3.

Since we are working on [JED4](https://github.com/joomla/com_jed4) where you will be able to also contribute directly. We need your help... so please start looking over the new JED4 and make our contributions there.
