### ISSUE TITLE
View error code - link error

### ISSUE THREAD

**Issue by openexcel** [joomla/jed-issues#245]
When I clicked on the link text "View error codes" on this page: 
https://extensions.joomla.org/extension/access-a-security/site-security/jhackguard
the url link is to
http://extensions.joomla.org/support/knowledgebase/item/unpublished-extensions-error-codes

That page is blank and the correct url is: 
https://extensions.joomla.org/support/knowledgebase/error-codes/submission-error-codes

**Comment by toivo** [comment]
This is the correct URL:
https://extensions.joomla.org/support/knowledgebase/error-codes/unpublished-extensions-error-codes/

This issue was reported on 11 January at https://github.com/joomla/jed-issues/issues/243 and it was first reported two months ago at https://forum.joomla.org/viewtopic.php?f=262&t=990655
