### ISSUE TITLE
Ticket system not monitored?

### ISSUE THREAD

**Issue by minitek** [joomla/jed-issues#262]
Hi there,

The ticket system seems to be abandoned. I opened a ticket in JED 1 month ago and have not received any reply yet. 
I understand that people who reply to messages are volunteers, but the current system is inefficient.

Here is an idea. Introduce a monthly fee for commercial extensions. Popular commercial extensions could pay more.
Most of these developers make a lot of money from JED. They can afford to give something back and support the volunteers.

I have commercial extensions in JED and would not mind paying a fee for the privilege.

**Comment by webgobe** [comment]
No, the ticket system is not abandoned. We just are seriously understaffed. I am not seeing any ticket coming from you in an unanswered state. Can you please give me your ticket's ID to check what's up? If is someone else's desk, at least I will ask the colleague responsible for this to handle it. 
The only category with a backlog of 21 tickets in various stages of handling is the Listings - issues related to new listings OR listings which have been unpublished for various reasons and awaiting to be re-instantiated. All other categories have all tickets answered and up to date as I write this.

**Comment by minitek** [comment]
Thanks for replying.
I opened the ticket REVIEWS-FS1AB6759P back in 24/03. 
It's still open and I have not received any reply.

It's about a review on one of my free extensions. The reviewer is rating the commercial version. This should not be allowed according to the JED review policy but somehow the review was accepted and, to make matters worse, due to the fact that it's the most recent one, it has an extremely skewed weight and drops the extension rating down to 4/5 even though all previous 40+ reviews were 5/5.

**Comment by webgobe** [comment]
OK, I can't even see the reviews - that's someone else's desk, I don't have access to it, but I'll contact them to see what's up. What I can tell you about the technical side of this is that the review system is one of weakest parts of JED3 and we had a great number of issues especially related to calculation of scores. As far as I know that part was not changed/fixed for years, JED3 currently is in a brain death phase, was only patched for skin-deep issues for years. The actual state of the reviews system is a result of such a patch done about 4-5 years ago, following a heated debate related to the issues with the previous  algo used for calculating the score. We have a single person in team who actively develops the new JED4 so when (or even IF) this will replace the current system is a big open question. We are asking for help and support to get help from the community to keep this JED thing alive for years, but the situation is just getting worse. So I can't promise here to you anything above the fact that I will do everything I can to draw the issue with your ticket in the right person's attention.  
PS. I KNOW that this will not comfort you, but one of my FREE entries in JED - a plugin to extend the capabilities of a commercial extension -  has received a very low score, because the reviewer considered that it is overpriced... The review is still there, for more than 10 years for now, because back then I missed the deadline to reclaim being a bullshit review. More exactly when someone from the JED team of the time has touched it, was too late for that time's active rules. Was one of my bad experiences pushing me to volunteer for JED in idea to make the change from inside. And I have many similar stories. There are good people working here - but we are far under the desirable, optimal  number. There is no glory, no rewards or satisfaction to volunteer for JED. But nobody seems to care.

**Comment by minitek** [comment]
Thanks for helping. I appreciate it.

If there is anything I can do to help, please let me know.
