### ISSUE TITLE
Can not login into extensions.joomla.org

### ISSUE THREAD

**Issue by maxpa1n87** [joomla/jed-issues#27]
Hello Webmaster-Team,

I can not login anymore with my username maxpa1n87 on extensions.joomla.org.
Trying to reset the password with all my known email addresses, I get only the message that the email is invalid. Can somebody figure out what my email address was during registration and send me a PM on github please.

Sincerely,

maxpa1n87

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for developers of extensions listed on JED - we are unable to provide support for your issue here. For JED support questions, you can go to https://extensions.joomla.org/support/support-tickets/.

P.S. Please, create a second account and send a ticket with the full details of your original account.

Kind Regards
