### ISSUE TITLE
Number of items per page messing up results

### ISSUE THREAD

**Issue by jonrz** [joomla/jed-issues#29]
While searching for a particular module, I went to the JED, added the tag "K2 Extensions", nothing else, and hit search.

It displayed 5 items per page, with the pagination going to 48 (so about 237 results).

I then tried to change the number of items per page to 50, so my browsing would be easier, and it not only didn't show 50 per page, but it displayed just 4 results, and no pagination, plus reverted the URL to https://extensions.joomla.org/extensions/extension (instead of the long one with all the filters).

My tag appear to be lost/invisible sometimes, but it is there, because I can't add it again (not on the list, because it is already used).

I was able to make the "items per page" selector work by (and this is _interesting_, to say the least) changing to 50, seeing the bad results page (with only 4 extensions) hitting back in the browser, and then CTRL+F5 the page.

**Comment by anibalsanchez** [comment]
We have merged a fix related to pagination. Thanks, @jreviews 

Still, the pagination remembers the page position from previous navigation. Additionally, when the user selects a page size, it renders the pages numbers OK. But, when the user visits a page, the page limit goes back to the original value.

So, I think this issue is still active.

**Comment by anibalsanchez** [comment]
After the latest updates, I can no longer reproduce the issue. When the user navigates, the pagination remembers the page limit.
