### ISSUE TITLE
Images not showing on JED live site

### ISSUE THREAD

**Issue by vishalCTUK** [joomla/jed-issues#30]
No extension images on JED on different machines https://extensions.joomla.org/category/clients-a-communities/project-a-task-management/ img source <img src="//extensionscdn.joomla.org/cache/fab_image/56cf41a609194_resizeDown302px133px16.jpg" alt="Timesheet" class="mainimage">

**Comment by Kubik-Rubik** [comment]
The problem is that the CDN domain (https://extensionscdn.joomla.org) does not have a valid SSL certificate.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1976103/34156889-76f407f0-e4bf-11e7-97bb-28e2f819a328.png">

@anibalsanchez @mbabker Who is responsible for this domain?

**Comment by anibalsanchez** [comment]
Hi  @Kubik-Rubik ,

I sent a ticket to Rochen in the morning, and it looks fine now from my side now.

Could it be a caching issue now?

**Comment by Sotiris-k** [comment]
![image](https://user-images.githubusercontent.com/4454324/34157460-43926aa4-e4ca-11e7-84ad-90de02fd2c7e.png)

I believe cache isn't supposed to affect certificates.

**Comment by anibalsanchez** [comment]
I've also disabled the CDN until we confirm that they fix the certificate.

**Comment by vishalCTUK** [comment]
Loading images now. Thanks everyone.
