### ISSUE TITLE
Rating numbers and count of reviews are not accurate

### ISSUE THREAD

**Issue by frankmayer** [joomla/jed-issues#32]
I noticed that the rating numbers for extensions are not accurate. This is especially noticeable on newer extensions with one review.

There are plenty of examples. but you can look at mine: https://extensions.joomla.org/extensions/extension/core-enhancements/performance/fmj-blank-view/

In this example, the user rated all four points with a hundred percent. The rating summary on the right says 93 on each of the four points and a total of 73, which does not make any sense.

The problems seems to affext both free and paid extensions.

**Comment by Sotiris-k** [comment]
AFAIK this is how the rating system works in general by design.

**Comment by frankmayer** [comment]
Unless I am missing some important details, this design seems to not do correct calculations on rating averages. Both, for the rated points (that is, what all users rated for a specific point, like "Functionality" or "Documentation"), as well as for the overall average of all points rated.

**Comment by marcobeierer** [comment]
Newer free extensions can just get an overall rating of 83. I guess the calculation always takes the _Value for money_ into account, which is always 0 for free extensions because it could not be rated.

Older free extensions (added somewhere before 2015) seem not to have this issue, they could get higher overal ratings.

The difference between free and paid extensions is for example clearly visible in the [Site map category](https://extensions.joomla.org/tags/site-map/).

I noticed this for the first time in 2015 and there were also open bug reports in the old issue tracker at the time.

**Comment by anibalsanchez** [comment]
Hi,

Please, check this slide about how the review score is calculated: https://docs.google.com/presentation/d/1YTUvhYEK-bxoEE5-vJsjv06kZAvhpsAjSRmsY2w9GkU/edit#slide=id.g21ec0048aa_0_8

We can discuss how to change the algorithm, but it is currently working as it was designed. So, it's not really an open issue.

**Comment by marcobeierer** [comment]
Hi @anibalsanchez 

Thank you for your reply. I had a look at the explanation, but still think there is an issue with free extension created in 2015 or later.

If you use the JED search function and search for free extension ordered by 'Latest added', you will find nearly no extension with an overall score over 83. Just around 5 percent of the extensions have a higher overall score. 

And if you search for paid extensions ordered by 'Latest added', nearly all have an overall rating between 90 and 100.

The single ratings for paid and free extensions do not differ much so that this will not explain the differences.

Have for example a look at the following randomly picked extensions. One is free, one is paid, both have a similar rating profile, but the overall rating is different.

- https://extensions.joomla.org/extensions/extension/contacts-and-feedback/contact-details/azdirectory/
- https://extensions.joomla.org/extensions/extension/structure-a-navigation/site-map/ping-search-engines-on-sitemap-update/

---

Is it possible to have a look at the rating algorithm? I did a quick research but could not find the source code of the JED...

**Comment by anibalsanchez** [comment]
Hi,

The original author of the code is no longer on the team. For my [presentation at JAB16](https://www.youtube.com/watch?v=KyD1i8hVgpY), I read the code to answer the frequent questions, but I didn't do data analysis or simulation.

If you want to join the team of JED Devs, and look in detail into the code to propose an alternative, the Joomla community will be more than grateful: https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

**Comment by marcobeierer** [comment]
Hi @anibalsanchez 

Thank you for your reply.

I do not like to join the JED team permanently as I do not actively use Joomla anymore and have another focus currently, but I'm willing to help from time to time.

I just registered at JIRA and signed the contribution agreement. Do I have to open an issue on Bitbucket or could this GitHub issue be used for further discussion?

**Comment by anibalsanchez** [comment]
Hi @marcobeierer , you can contribute in the way that better suits you. 

We have moved away from JIRA and today we manage the full process on Github.

Do you have a Glip account to add you to the JED Dev Chat?

P.S. Tomorrow I'm going to clean all references to JIRA from JED.

**Comment by anibalsanchez** [comment]
@marcobeierer Just in case, I sent you an invitation to your gmail.

**Comment by marcobeierer** [comment]
@anibalsanchez I think this issue can be closed now.

**Comment by anibalsanchez** [comment]
Yes, the issue is solved and the enhancement published on the live site. Thank you!

BTW: A new Instant Search is coming to the live site. If you want to help testing it, it's implemented in staging. For more information, please, visit #37
