### ISSUE TITLE
Different urls for one extension

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#56]
From Jira: https://joomlaextensionsdirectory.atlassian.net/projects/JDEV/issues/JDEV-1045

There is a SEO issue in JED sitemap which causes duplicate address for the same listing.
E.g I've recently submitted my module, its url in website is different from the url in the sitemap.xml

In website: http://extensions.joomla.org/extensions/extension/living/religious-events/grand-prayer-times
In sitemap.xml : http://extensions.joomla.org/extension/grand-prayer-times

This issue is present with other listings too.

**Comment by jreviews** [comment]
Just noticed the same thing with my newly submitted JReviews extension and the problem is not only with the sitemap. If you do a search and pick from the live search results below the keyword search, the result looks like this:

[https://extensions.joomla.org/extension/jreviews/](https://extensions.joomla.org/extension/jreviews/)

If instead, you hit "enter" or click the "Go" button and then use the link from the results page, it looks like this:

[https://extensions.joomla.org/extensions/extension/directory-a-documentation/directory/jreviews/](https://extensions.joomla.org/extensions/extension/directory-a-documentation/directory/jreviews/)

I think the easiest solution would be to add a canonical tag on the longer URL that points to the shorter one or vice-versa.

**Comment by anibalsanchez** [comment]
Fixed with a redirection
