### ISSUE TITLE
Wrong extensions list sorting

### ISSUE THREAD

**Issue by ZyXoid** [joomla/jed-issues#64]
Hi.
The sorting of the extensions is strange.
Check out the attached screenshot 
![screenshot_1](https://user-images.githubusercontent.com/3471561/50507797-aa90f480-0a87-11e9-8b50-a278bd9d3991.jpg)

As far as i can see, the extension are sorted inside the category be the rating and number of reviews. But i found in the category "Social display" on the second page: https://extensions.joomla.org/category/social-web/social-display/?start=12 there are extensions that must be higher in the list.

**Comment by anibalsanchez** [comment]
Hi,

By default, the extensions are sorted by the review score, a total index. Please, check this slide about how the review score is calculated: https://docs.google.com/presentation/d/1YTUvhYEK-bxoEE5-vJsjv06kZAvhpsAjSRmsY2w9GkU/edit#slide=id.g21ec0048aa_0_8

Since this is a definition by design, there is no issue and it is working as expected.
