### ISSUE TITLE
Bug or rating change ? (ranking by stars and reviews)

### ISSUE THREAD

**Issue by cyrez** [joomla/jed-issues#84]
Just a few days ago, my extension _iCagenda_ was 3rd in the standings for the category **Calendars & Events**: https://extensions.joomla.org/category/calendars-a-events/

That was ok: 5 stars and 154 reviews.

With no changes in rating (stars) and number of reviews for all top extensions of this category in last days, my extension is now on 16th position... :-|

I see the same issue appeared in **Galleries** category: https://extensions.joomla.org/category/photos-a-images/galleries/
Here, _Ozio Gallery_, previously 1st, is now on 33rd position (second page).

Maybe other categories and overall ranking are affected.

So, is it a bug or a rating change ?
As a visitor, seems a bit unclear... when checking number of stars and reviews, for top rated extensions.

**Comment by anibalsanchez** [comment]
We haven't changed the rating.

Please, take into account that the rating changes with time (Freshness factor). Please, check these slides with a high-level description: 

https://docs.google.com/presentation/d/1YTUvhYEK-bxoEE5-vJsjv06kZAvhpsAjSRmsY2w9GkU/edit#slide=id.g21ec0048aa_0_8

https://www.youtube.com/watch?v=KyD1i8hVgpY

**Comment by cyrez** [comment]
> rating changes with time

Well, so how an extension with 9 reviews, **latest review 4 years ago** (and latest update 3 years ago) could be ranked top of mine with 5 stars and 154 reviews ?... :-|

**Comment by marcobeierer** [comment]
Hi @anibalsanchez 

I have not checked the reported situation, but it seems that something doesn't work correctly in the rating system. The rating of one of my extensions also seems to be incorrect, namely the rating of my Sitemap Generator (https://extensions.joomla.org/extensions/extension/structure-a-navigation/site-map/sitemap-generator/).

I did some calculations and took the freshness into account and the overall score should be over 4, but is currently shown as 3. The score for the documentation should be over 2.5, but is shown as 1.5.

I'm not sure when this happend. The Sitemap Generator got one bad review in March 2018 and if I remember right, afterwards it had about the current rating.

However, in December 2018 it got a 5 star review which has not significantly changed the rating despite the bad review lost freshness in the meantime.

I will have a closer look at this if I find the time. I just had a short look but the code for the calculation is very hard to read and follow because of the coding style.

Maybe it would also be a good idea to discuss freshness in general. In the current implementation freshness has a very high impact and one bad review can kill an extension even it just had 5 star reviews in the past...

My Sitemap Generator for example had eighteen five star reviews, one 4.5 star review, two four star reviews and one one star review. Then it got another one star review and the overall score dropped significantly and so did the interest in the extension because it was listed last in its category...

---

@JoomliC 
The freshness is calculated by `25 minus [age of review in month]`, then the score is multiplied with the freshness which results in the weight given to the score.

This means that if all reviews are old, they all have the same weight and thus the overall score can be high.

But for example if you have 24 five star reviews that are two years old and one recent 1 star review, the 24 old reviews have together the same weight as the 1 star review and the new average is just 3.

**Comment by anibalsanchez** [comment]
The current algorithm has been running without changes for ages. The last change was your improvement @marcobeierer .

We could create a new algorithm, and I'm in favor of improvements and new features. For instance, I would like to add a **mobile-first factor**, to improve the ranking of "modern extensions". However, it is a process that must be backed by the whole community of developers. 

To be clear, it is not a change/ improvement to benefit the rank of one extension or a particular case. So, probably a new implementation would not change the current numeric values of the same extensions. A new implementation would keep the current values, discover new benefits that are currently hidden or encourage the development in the **mobile-first / modern** development.

**Comment by marcobeierer** [comment]
Thank you @anibalsanchez for your reply and the explanation.

I will first check if there is a bug in the current calculation and fix it if so.

Then I will have a look if I have some ideas to refactor the score calculation to make it more readable and easier to work with in the future. If I have an idea, should I make a short proposal first?

Afterwards we can think about a new algorithm and the process to back it by the community. But it could take some time till I find the time to tackle such a complex matter.

**Comment by cyrez** [comment]
> The current algorithm has been running without changes for ages.

@anibalsanchez Not there for ages, but for 4 years and 5 months... ;-)

I don't think we should create a new algorithm, but to improve it.

**The freshness factor starts to show some issues**, as i don't think that yourself, you will see as normal that an extension with 9 reviews, latest 4 years ago, no updates since years, and not all reviews at 5 stars to be ranked top of an extension with 154 reviews, latest this year, and a 5 stars average ranking.

The freshness factor starts to kill ranking of extensions with a lot of reviews in favor of extensions with no reviews since years.
There i see a problem that will grow time by time...

So maybe just need to be adjusted ;-)

@marcobeierer I don't have yet check your explanation at how the system work, seems a bit fancy... but as you said, result could be wrong (at least not fair).
I will check when a bit of time. ;-)

**Comment by anibalsanchez** [comment]
I've recently (May 1st) updated the [JED Search use cases and definitions
](https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions).

**Comment by beat** [comment]
We are facing a real problem here that is hurting Joomla users, that sometimes can't find popular extensions that are reviewed a lot, and that can suddenly put off the records extensions with a small amount of reviews, or extensions with lots of reviews that suddenly receive a not-perfect all-5-stars-in-all-categories review.
The "Top ranking" and "Category ranking" sorting criteria should be doing a coarser rounding on the average rating (at least to the half-point if not to the point). Otherwise the top ranking is a gamble imho.
This is no small issue, as it can hurt really badly extensions for a minor imperfect review.
How can we improve this ?
Should the average rating used for sorting just be rounded to the nearest integer value before sorting ?

**Comment by beat** [comment]
Hi @anibalsanchez, can I please volunteer to have access to the JED code to try to propose a PR for code improvement to implement the above-proposed floating-number rounding fix ?

Having top extensions disappearing randomly from top results because of a floating number rounding issue hurts not only extensions-developers survival, but also immensely Joomla and its community. And this is highly visible in Joomla's Google-Trends.

**Comment by anibalsanchez** [comment]
Sure, we are always open to new JED Developers. 

In the past year, we implemented a few improvements, but it is an ongoing task that needs attention.

Please, contact me on Glip to start the onboarding process.

**Comment by marcobeierer** [comment]
Hi @beat 

I think this is not just a rounding issue, but a much deeper calculation issue.

There also seems to be an issue with unrated categories. For me it seems that sometimes if a category (for example Documentation) is not rated, it is used anyway as 0 value in the average calculation for this category.

From what I see from the outside, not all extensions seem to be affected by this, maybe there is some inconsistency in the data, like sometimes unrated categories have a 0 value and sometimes are NULL.

I have two good example extensions if you are interested and if there is an up to date data dump available when you working on it.

I just recently decided to stop the active development on both my affected extensions because the number of new users dropped significantly because of rating calculation issues and I was not able to compensate it otherwise.

**Comment by beat** [comment]
Hi @marcobeierer
Thanks for the heads-up.
I will be doing a review of the (open-source) algorithm source once I get access to it (normally tomorrow).

**Comment by cyrez** [comment]
The freshness factor sucks too...
https://github.com/joomla/jed-issues/issues/84#issuecomment-473526662



> I just recently decided to stop the active development on both my affected extensions because the number of new users dropped significantly because of rating calculation issues and I was not able to compensate it otherwise.

I understand this so much as i'm affected too... Less visits from JED (since new JED) = less income = need to find other jobs = no more time to contribute to Joomla CMS... (so bad for Joomla as a whole as i'm not the only one to be in this situation since the new JED was introduced...)

**Comment by regularlabs** [comment]
Yup, definitely something wrong.
This extension of mine now has a rating of 2 stars for 'Support'.
https://extensions.joomla.org/extension/better-preview/

There are only 4 reviews that score the Support. 3 times a 5-stars and 1 time a 4.5-star.
I don't think a 'freshness factor' can turn that into a 2-star rating.

**Comment by marcobeierer** [comment]
@regularlabs According to the presentation linked by @anibalsanchez above (https://docs.google.com/presentation/d/1YTUvhYEK-bxoEE5-vJsjv06kZAvhpsAjSRmsY2w9GkU/edit#slide=id.g21ec0048aa_0_0) the freshness factor only has an impact on the weighting of the ratings, thus it should not be able to decrease the overall score of a category below the lowest score in this category, in your case 4.5.

There is also the bonus-malus-ratio that ads a bonus or malus depending on the number of reviews, but if I remember right, it is just applied on the overall score of the extension, not the overall scores of the categories.

**Comment by regularlabs** [comment]
Exactly.
So clearly something broken.
But there seems to be no will or readiness to fix this!

**Comment by anibalsanchez** [comment]
We have the will.... but no time. If you can collaborate in the solution, the doors are always open.

After FFTF, we are exploring other alternatives to maintaining the system. I'll update you as soon as we have news.

**Comment by regularlabs** [comment]
I think it is about allocation of time.
You could argue that something like this is vital to the system and service provided by the JED.
So it should take precedence over time spent on dealing with new listing requests.
Just shut down new requests until major issues are dealt with.

**Comment by anibalsanchez** [comment]
The volunteers that operate the system are not the same that develop/maintain the system. 

The task of fixing bugs waits until a developer finds the time. Since it is not so enjoyable, there are only a few that actually submit improvements in their free time.

**Comment by regularlabs** [comment]
Ok.

**Comment by minitek** [comment]
Hi guys, is anyone working on this? The problem still exists. Popular and quality extensions are buried under a mountain of crappy extensions with one 5-star review.

**Comment by anibalsanchez** [comment]
We are not currently planning a change in the current rating algorithm. It is a time-consuming task that requires to dig in the history of reviews and the current data set.

@minitek If you want to investigate the case, please, contact me to join the JED devs team, I can facilitate you a recent dump and the development site.

**Comment by minitek** [comment]
Hi Anibal, 
I would like to join the JED devs team. That would be great. I can look into it and propose some improvements.

**Comment by anibalsanchez** [comment]
Please, send me an email (anibal.sanchez [@] extensions.joomla.org) to start the onboarding process, add you to the Glip group, etc

**Comment by anibalsanchez** [comment]
Hi,

I've been recently re-checking the scores. It seems that due to a confusion between scores not being entered or people choosing to not enter scores, there were 0, -1 and null values in the review ratings and they are not shown in the front-end. So, it is not clear what the user enters, it is open to interpretation and the score is affected by values that are not shown on the page.

Since it only affects less than 2% of the extensions, I've applied a fix to ignore the 0, -1 and null values. The change slightly improves the score of some extensions and fixes the issue in the extensions with a few reviews (that are more affected by the issue).

Please, check the score and report back if you find that the issue remains active.

**Comment by marcobeierer** [comment]
@anibalsanchez 
Thank you for your effort and sorry for my late reply.

I had a quick look at my extensions and the ratings seem more accurate now, but I have not checked them in detail...

**Comment by anibalsanchez** [comment]
Great. Glad to be helpful.
